In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [3]:
numerical = pd.read_csv('numerical.csv')
categorical = pd.read_csv('categorical.csv')
target= pd.read_csv('target.csv')

In [4]:
numerical

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
0          0  60.000000       5        9    0         0       39        34   
1          1  46.000000       6        9   16         0       15        55   
2          1  61.611649       3        1    2         0       20        29   
3          0  70.000000       1        4    2         0       23        14   
4          0  78.000000       3        2   60         1       28         9   
...      ...        ...     ...      ...  ...       ...      ...       ...   
95407      1  61.611649       5        9    0        14       36        47   
95408      1  48.000000       7        9    1         0       31        43   
95409      1  60.000000       5        9    0         0       18        46   
95410      0  58.000000       7        9    0         0       28        35   
95411      2  80.000000       5        8    3         1       33        22   

       WWIIVETS  LOCALGOV  ...  CARDGIFT  MINRAMNT  MAXRAMNT  LASTGIFT  \
0            18        10  ...        14       5.0      12.0      10.0   
1            11         6  ...         1      10.0      25.0      25.0   
2            33         6  ...        14       2.0      16.0       5.0   
3            31         3  ...         7       2.0      11.0      10.0   
4            53        26  ...         8       3.0      15.0      15.0   
...         ...       ...  ...       ...       ...       ...       ...   
95407        11         7  ...         0      25.0      25.0      25.0   
95408        19         4  ...         0      20.0      20.0      20.0   
95409        20         7  ...         4       3.0      10.0      10.0   
95410        20         9  ...        18       5.0      21.0      18.0   
95411        27         8  ...        11      10.0     201.0     100.0   

       TIMELAG    AVGGIFT  CONTROLN  HPHONE_D  RFA_2F  CLUSTER2  
0            4   7.741935     95515         0       4        39  
1           18  15.666667    148535         0       2         1  
2           12   7.481481     15078         1       4        60  
3            9   6.812500    172556         1       4        41  
4           14   6.864865      7112         1       2        26  
...        ...        ...       ...       ...     ...       ...  
95407        9  25.000000    184568         0       1        12  
95408        9  20.000000    122706         1       1         2  
95409        3   8.285714    189641         1       3        34  
95410        4  12.146341      4693         1       4        11  
95411        6  96.794872    185114         1       1        12  

[95412 rows x 315 columns]

In [5]:
numerical.isna().sum().sum()

0

In [6]:
numerical.columns

Index(['TCODE', 'AGE', 'INCOME', 'WEALTH1', 'HIT', 'MALEMILI', 'MALEVET',
       'VIETVETS', 'WWIIVETS', 'LOCALGOV',
       ...
       'CARDGIFT', 'MINRAMNT', 'MAXRAMNT', 'LASTGIFT', 'TIMELAG', 'AVGGIFT',
       'CONTROLN', 'HPHONE_D', 'RFA_2F', 'CLUSTER2'],
      dtype='object', length=315)

In [7]:
categorical

STATE  CLUSTER HOMEOWNR GENDER  DATASRCE RFA_2R RFA_2A GEOCODE2  \
0         IL       36        H      F         3      L      E        C   
1         CA       14        H      M         3      L      G        A   
2         NC       43        U      M         3      L      E        C   
3         CA       44        U      F         3      L      E        C   
4         FL       16        H      F         3      L      F        A   
...      ...      ...      ...    ...       ...    ...    ...      ...   
95407  other       27        H      M         3      L      G        C   
95408     TX       24        H      M         3      L      F        A   
95409     MI       30        H      M         3      L      E        B   
95410     CA       24        H      F         2      L      F        A   
95411     NC       24        U      F         3      L      G        C   

      DOMAIN_A  DOMAIN_B  ...  DOB_YR  DOB_MM  MINRDATE_YR  MINRDATE_MM  \
0            T         2  ...      37      12           92            8   
1            S         1  ...      52       2           93           10   
2            R         2  ...       0       2           91           11   
3            R         2  ...      28       1           87           11   
4            S         2  ...      20       1           93           10   
...        ...       ...  ...     ...     ...          ...          ...   
95407        C         2  ...       0       2           96            2   
95408        C         1  ...      50       1           96            3   
95409        C         3  ...      38       1           96            3   
95410        C         1  ...      40       5           90           11   
95411        C         1  ...      18       1           88           12   

       MAXRDATE_YR  MAXRDATE_MM  LASTDATE_YR  LASTDATE_MM  FIRSTDATE_YR  \
0               94            2           95           12            89   
1               95           12           95           12            93   
2               92            7           95           12            90   
3               94           11           95           12            87   
4               96            1           96            1            79   
...            ...          ...          ...          ...           ...   
95407           96            2           96            2            96   
95408           96            3           96            3            96   
95409           95            1           96           10            94   
95410           96            8           97            1            86   
95411           93           12           96           12            88   

       FIRSTDATE_MM  
0                11  
1                10  
2                 1  
3                 2  
4                 3  
...             ...  
95407             2  
95408             3  
95409            10  
95410            12  
95411             3  

[95412 rows x 22 columns]

In [8]:
categorical.isna().sum().sum()

0

In [9]:
categorical.columns

Index(['STATE', 'CLUSTER', 'HOMEOWNR', 'GENDER', 'DATASRCE', 'RFA_2R',
       'RFA_2A', 'GEOCODE2', 'DOMAIN_A', 'DOMAIN_B', 'ODATEW_YR', 'ODATEW_MM',
       'DOB_YR', 'DOB_MM', 'MINRDATE_YR', 'MINRDATE_MM', 'MAXRDATE_YR',
       'MAXRDATE_MM', 'LASTDATE_YR', 'LASTDATE_MM', 'FIRSTDATE_YR',
       'FIRSTDATE_MM'],
      dtype='object')

In [10]:
target

TARGET_B  TARGET_D
0             0       0.0
1             0       0.0
2             0       0.0
3             0       0.0
4             0       0.0
...         ...       ...
95407         0       0.0
95408         0       0.0
95409         0       0.0
95410         1      18.0
95411         0       0.0

[95412 rows x 2 columns]

In [11]:
target.isna().sum().sum()

0

In [12]:
data = pd.concat([numerical, categorical, target], axis = 1)
data['TARGET_B'].value_counts()

0    90569
1     4843
Name: TARGET_B, dtype: int64

In [13]:
data.shape

(95412, 339)

In [14]:
data.isna().sum().sum()

0

In [15]:
data.head()

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
0      0  60.000000       5        9    0         0       39        34   
1      1  46.000000       6        9   16         0       15        55   
2      1  61.611649       3        1    2         0       20        29   
3      0  70.000000       1        4    2         0       23        14   
4      0  78.000000       3        2   60         1       28         9   

   WWIIVETS  LOCALGOV  ...  MINRDATE_YR  MINRDATE_MM  MAXRDATE_YR  \
0        18        10  ...           92            8           94   
1        11         6  ...           93           10           95   
2        33         6  ...           91           11           92   
3        31         3  ...           87           11           94   
4        53        26  ...           93           10           96   

   MAXRDATE_MM  LASTDATE_YR  LASTDATE_MM  FIRSTDATE_YR  FIRSTDATE_MM  \
0            2           95           12            89            11   
1           12           95           12            93            10   
2            7           95           12            90             1   
3           11           95           12            87             2   
4            1           96            1            79             3   

   TARGET_B  TARGET_D  
0         0       0.0  
1         0       0.0  
2         0       0.0  
3         0       0.0  
4         0       0.0  

[5 rows x 339 columns]

In [16]:
data = data.drop(['TARGET_D'], axis=1)

# X,y split and Train-Test Split

In [17]:
y = data['TARGET_B']
X = data.drop(['TARGET_B'], axis = 1) 

# Note: we need to do train/test split before upsampling
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

numericalX_train   = X_train.select_dtypes(np.number)
numericalX_test    = X_test.select_dtypes(np.number)
categoricalX_train = X_train.select_dtypes(object) 
categoricalX_test  = X_test.select_dtypes(object) 

# we OneHotEncode the categoricals so we can use the same dataset to perform a regression later (in the lab).
# it is not needed for a DecisionTree or RandomForest model
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(categoricalX_train)
encoded_categorical_train = encoder.transform(categoricalX_train).toarray()
encoded_categorical_train = pd.DataFrame(encoded_categorical_train, columns=encoder.get_feature_names_out()) # needed to avoid error
encoded_categorical_test = encoder.transform(categoricalX_test).toarray()
encoded_categorical_test = pd.DataFrame(encoded_categorical_test, columns=encoder.get_feature_names_out())

# we scale the numericals so we can use the same dataset to perform a regression later (in the lab).
# it is not needed for a DecisionTree or RandomForest model
from sklearn.preprocessing import MinMaxScaler
transformer = MinMaxScaler().fit(numericalX_train)
scaled_numerical_train = transformer.transform(numericalX_train)
scaled_numerical_train = pd.DataFrame(scaled_numerical_train, columns=numericalX_train.columns)
scaled_numerical_test  = transformer.transform(numericalX_test)
scaled_numerical_test  = pd.DataFrame(scaled_numerical_test, columns=numericalX_train.columns)

X_train_treated = pd.concat([scaled_numerical_train, encoded_categorical_train], axis = 1)
X_test_treated  = pd.concat([scaled_numerical_test,  encoded_categorical_test],  axis = 1)

In [18]:
display(X_train_treated.head())
display(y_train)

TCODE       AGE    INCOME   WEALTH1       HIT  MALEMILI   MALEVET  \
0  0.000017  0.762887  0.500000  0.666667  0.008299  0.000000  0.313131   
1  0.000000  0.536082  0.666667  1.000000  0.000000  0.000000  0.292929   
2  0.000017  0.608247  0.666667  0.111111  0.020747  0.000000  0.424242   
3  0.000017  0.783505  0.833333  0.666667  0.037344  0.010101  0.404040   
4  0.000052  0.556701  0.666667  0.222222  0.087137  0.333333  0.272727   

   VIETVETS  WWIIVETS  LOCALGOV  ...  RFA_2A_E  RFA_2A_F  RFA_2A_G  \
0  0.101010  0.686869  0.060606  ...       0.0       0.0       0.0   
1  0.242424  0.383838  0.070707  ...       0.0       1.0       0.0   
2  0.161616  0.626263  0.101010  ...       1.0       0.0       0.0   
3  0.232323  0.414141  0.080808  ...       0.0       1.0       0.0   
4  0.292929  0.181818  0.121212  ...       0.0       1.0       0.0   

   GEOCODE2_B  GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  \
0         1.0         0.0         0.0         0.0         0.0         0.0   
1         0.0         1.0         0.0         1.0         0.0         0.0   
2         0.0         0.0         0.0         0.0         0.0         0.0   
3         0.0         0.0         0.0         0.0         0.0         0.0   
4         1.0         0.0         0.0         0.0         0.0         0.0   

   DOMAIN_A_U  
0         0.0  
1         0.0  
2         0.0  
3         1.0  
4         0.0  

[5 rows x 354 columns]

79401    0
86429    0
76729    1
38838    0
83012    0
        ..
21243    0
45891    0
42613    1
43567    0
68268    0
Name: TARGET_B, Length: 76329, dtype: int64

In [19]:
# for upsampling we need to temporarily concat X_train and y_train
# need to reset_index on y_train to make sure they line up
trainset = pd.concat([X_train_treated, y_train.reset_index(drop=True)], axis=1)

In [20]:
trainset

TCODE       AGE    INCOME   WEALTH1       HIT  MALEMILI   MALEVET  \
0      0.000017  0.762887  0.500000  0.666667  0.008299  0.000000  0.313131   
1      0.000000  0.536082  0.666667  1.000000  0.000000  0.000000  0.292929   
2      0.000017  0.608247  0.666667  0.111111  0.020747  0.000000  0.424242   
3      0.000017  0.783505  0.833333  0.666667  0.037344  0.010101  0.404040   
4      0.000052  0.556701  0.666667  0.222222  0.087137  0.333333  0.272727   
...         ...       ...       ...       ...       ...       ...       ...   
76324  0.000000  0.711340  0.333333  1.000000  0.020747  0.020202  0.373737   
76325  0.000034  0.670103  0.333333  0.666667  0.000000  0.000000  0.363636   
76326  0.000017  0.624862  0.666667  1.000000  0.000000  0.000000  0.353535   
76327  0.000017  0.773196  0.666667  0.333333  0.004149  0.000000  0.595960   
76328  0.000000  0.624862  0.166667  1.000000  0.000000  0.000000  0.323232   

       VIETVETS  WWIIVETS  LOCALGOV  ...  RFA_2A_F  RFA_2A_G  GEOCODE2_B  \
0      0.101010  0.686869  0.060606  ...       0.0       0.0         1.0   
1      0.242424  0.383838  0.070707  ...       1.0       0.0         0.0   
2      0.161616  0.626263  0.101010  ...       0.0       0.0         0.0   
3      0.232323  0.414141  0.080808  ...       1.0       0.0         0.0   
4      0.292929  0.181818  0.121212  ...       1.0       0.0         1.0   
...         ...       ...       ...  ...       ...       ...         ...   
76324  0.101010  0.323232  0.262626  ...       0.0       0.0         1.0   
76325  0.111111  0.626263  0.040404  ...       1.0       0.0         0.0   
76326  0.292929  0.424242  0.171717  ...       0.0       0.0         0.0   
76327  0.222222  0.313131  0.030303  ...       0.0       1.0         0.0   
76328  0.262626  0.373737  0.030303  ...       0.0       0.0         0.0   

       GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  DOMAIN_A_U  \
0             0.0         0.0         0.0         0.0         0.0         0.0   
1             1.0         0.0         1.0         0.0         0.0         0.0   
2             0.0         0.0         0.0         0.0         0.0         0.0   
3             0.0         0.0         0.0         0.0         0.0         1.0   
4             0.0         0.0         0.0         0.0         0.0         0.0   
...           ...         ...         ...         ...         ...         ...   
76324         0.0         0.0         0.0         1.0         0.0         0.0   
76325         0.0         1.0         0.0         0.0         1.0         0.0   
76326         0.0         1.0         1.0         0.0         0.0         0.0   
76327         1.0         0.0         0.0         0.0         1.0         0.0   
76328         1.0         0.0         1.0         0.0         0.0         0.0   

       TARGET_B  
0             0  
1             0  
2             1  
3             0  
4             0  
...         ...  
76324         0  
76325         0  
76326         1  
76327         0  
76328         0  

[76329 rows x 355 columns]

# Treating the imbalance

In [21]:
trainset['TARGET_B'].value_counts()

0    72486
1     3843
Name: TARGET_B, dtype: int64

In [22]:
category_0 = trainset[trainset['TARGET_B']==0]
print(category_0.shape)

(72486, 355)


In [23]:
category_1 = trainset[trainset['TARGET_B']== 1 ]
print(category_1.shape)

(3843, 355)


In [24]:
category_1_upscaled = trainset[trainset['TARGET_B']==1].sample(len(trainset[trainset['TARGET_B']==0]),replace=True)
print(category_1_upscaled.shape)

(72486, 355)


In [25]:
trainset_new = pd.concat([category_1_upscaled, category_0], axis = 0)
trainset_new = trainset_new.sample(frac=1) #randomize the rows

In [26]:
X_train_treated_upsampled = trainset_new.drop(['TARGET_B'], axis=1)
y_train = trainset_new['TARGET_B']
print(X_train_treated_upsampled.shape)

(144972, 354)


In [27]:
y_test

58053    0
9484     0
13395    0
1466     0
2076     0
        ..
94255    0
26449    0
1969     0
48574    0
73270    0
Name: TARGET_B, Length: 19083, dtype: int64

In [28]:
X_test_treated

TCODE       AGE    INCOME   WEALTH1       HIT  MALEMILI   MALEVET  \
0      0.000483  0.659794  0.833333  1.000000  0.000000  0.000000  0.242424   
1      0.000017  0.587629  0.666667  1.000000  0.000000  0.000000  0.171717   
2      0.000017  0.463918  1.000000  0.888889  0.004149  0.000000  0.282828   
3      0.000000  0.624862  0.666667  1.000000  0.000000  0.000000  0.333333   
4      0.000000  0.463918  0.333333  0.222222  0.000000  0.494949  0.161616   
...         ...       ...       ...       ...       ...       ...       ...   
19078  0.000034  0.624862  0.166667  0.000000  0.000000  0.000000  0.313131   
19079  0.000000  0.690722  0.666667  0.222222  0.074689  0.000000  0.303030   
19080  0.000000  0.505155  0.666667  1.000000  0.000000  0.000000  0.222222   
19081  0.000000  0.624862  0.166667  0.222222  0.000000  0.000000  0.333333   
19082  0.000017  0.670103  0.833333  0.555556  0.008299  0.000000  0.343434   

       VIETVETS  WWIIVETS  LOCALGOV  ...  RFA_2A_E  RFA_2A_F  RFA_2A_G  \
0      0.424242  0.222222  0.090909  ...       0.0       1.0       0.0   
1      0.282828  0.424242  0.101010  ...       0.0       1.0       0.0   
2      0.444444  0.222222  0.020202  ...       0.0       0.0       1.0   
3      0.373737  0.494949  0.080808  ...       1.0       0.0       0.0   
4      0.323232  0.030303  0.090909  ...       0.0       1.0       0.0   
...         ...       ...       ...  ...       ...       ...       ...   
19078  0.262626  0.313131  0.060606  ...       1.0       0.0       0.0   
19079  0.232323  0.313131  0.070707  ...       0.0       1.0       0.0   
19080  0.121212  0.383838  0.080808  ...       0.0       1.0       0.0   
19081  0.262626  0.414141  0.121212  ...       1.0       0.0       0.0   
19082  0.292929  0.454545  0.131313  ...       1.0       0.0       0.0   

       GEOCODE2_B  GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  \
0             0.0         0.0         0.0         0.0         0.0         0.0   
1             0.0         0.0         0.0         0.0         0.0         0.0   
2             0.0         0.0         0.0         0.0         1.0         0.0   
3             0.0         0.0         0.0         0.0         0.0         1.0   
4             1.0         0.0         0.0         0.0         0.0         1.0   
...           ...         ...         ...         ...         ...         ...   
19078         0.0         0.0         1.0         1.0         0.0         0.0   
19079         0.0         1.0         0.0         0.0         0.0         0.0   
19080         0.0         0.0         1.0         1.0         0.0         0.0   
19081         0.0         0.0         1.0         0.0         0.0         1.0   
19082         0.0         0.0         1.0         0.0         0.0         1.0   

       DOMAIN_A_U  
0             0.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
19078         0.0  
19079         0.0  
19080         0.0  
19081         0.0  
19082         0.0  

[19083 rows x 354 columns]

# Random Forest Classifier

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5, # max number of questions to ask
                             min_samples_split=20, # amount of rows still considered at every question
                             min_samples_leaf =20, # ultimate answer based on at least this many rows
                             #max_samples=0.8, # fraction of X-train to use in each tree
                             random_state=42)
clf.fit(X_train_treated_upsampled, y_train)
print(clf.score(X_train_treated_upsampled, y_train))
print(clf.score(X_test_treated , y_test))

y_pred = clf.predict(X_test_treated )
display(y_test.value_counts())
display(confusion_matrix(y_test, y_pred))

0.6261071103385482
0.6009537284494052


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[10912,  7171],
       [  444,   556]])

# Cross Validation

In [30]:
# extra: how to select which metric to use in CV
# For cross validation
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(max_depth=5,
                             min_samples_split=20,
                             min_samples_leaf =20,
                            # max_samples=0.8
                            )
cross_val_scores = cross_val_score(clf, X_train_treated_upsampled, y_train, cv=10)
print(np.mean(cross_val_scores))

0.6201956007604353


In [31]:
cross_val_score(clf, X_train_treated_upsampled, y_train, cv=5, scoring='f1')

array([0.62664407, 0.62649538, 0.62591853, 0.62106346, 0.626952  ])

# FEATURE SELECTION

# Variance Threshold

Scaling the numericals

In [32]:
# to look at VarianceThresholds we need all the variable to be on the same scale
# we will use MinMaxScaler for this
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
numerical_scaled = scaler.fit_transform(numerical)

In [33]:
pd.DataFrame(numerical_scaled).head()

0         1         2         3         4         5         6    \
0  0.000000  0.608247  0.666667  1.000000  0.000000  0.000000  0.393939   
1  0.000014  0.463918  0.833333  1.000000  0.066390  0.000000  0.151515   
2  0.000014  0.624862  0.333333  0.111111  0.008299  0.000000  0.202020   
3  0.000000  0.711340  0.000000  0.444444  0.008299  0.000000  0.232323   
4  0.000000  0.793814  0.333333  0.222222  0.248963  0.010101  0.282828   

        7         8         9    ...       305    306       307    308  \
0  0.343434  0.181818  0.101010  ...  0.341463  0.005  0.001401  0.010   
1  0.555556  0.111111  0.060606  ...  0.024390  0.010  0.004004  0.025   
2  0.292929  0.333333  0.060606  ...  0.341463  0.002  0.002202  0.005   
3  0.141414  0.313131  0.030303  ...  0.170732  0.002  0.001201  0.010   
4  0.090909  0.535354  0.262626  ...  0.195122  0.003  0.002002  0.015   

        309       310       311  312       313       314  
0  0.003676  0.006465  0.498045  0.0  1.000000  0.622951  
1  0.016544  0.014399  0.774510  0.0  0.333333  0.000000  
2  0.011029  0.006204  0.078617  1.0  1.000000  0.967213  
3  0.008272  0.005534  0.899764  1.0  1.000000  0.655738  
4  0.012868  0.005586  0.037079  1.0  0.333333  0.409836  

[5 rows x 315 columns]

In [34]:
from sklearn.feature_selection import VarianceThreshold 
var_threshold = 0.02
sel = VarianceThreshold(threshold=(var_threshold))

# 1) default is threshold = 0 :eliminate all coumns that are identical for all rows
# 2) in practice we would scale the columns first, and then apply threshold, or apply 
#    a different threshold for different columns

# This drops the columns that have a variance less than this threshold
sel = sel.fit(numerical_scaled)
temp = sel.transform(numerical_scaled)
temp = pd.DataFrame(temp)
print(numerical_scaled.shape)
print(temp.shape)

(95412, 315)
(95412, 79)


In [35]:
# we dropped (315 - 236 =79) of our columns columns
pd.DataFrame(temp).head()

0         1         2         3         4         5    6         7   \
0  0.608247  0.666667  1.000000  0.343434  0.181818  0.555556  0.0  0.353535   
1  0.463918  0.833333  1.000000  0.555556  0.111111  1.000000  1.0  0.000000   
2  0.624862  0.333333  0.111111  0.292929  0.333333  0.111111  0.0  0.020202   
3  0.711340  0.000000  0.444444  0.141414  0.313131  0.000000  0.0  0.080808   
4  0.793814  0.333333  0.222222  0.090909  0.535354  1.000000  1.0  0.000000   

         8         9   ...        69        70        71        72   73  \
0  0.656566  0.929293  ...  0.333333  0.656566  0.404040  0.285714  0.4   
1  0.000000  0.676768  ...  1.000000  0.000000  1.000000  0.952381  0.8   
2  0.989899  0.969697  ...  0.222222  0.777778  0.171717  0.428571  0.4   
3  0.929293  0.616162  ...  0.232323  0.777778  0.222222  0.761905  0.4   
4  0.000000  0.020202  ...  1.000000  0.010101  0.212121  0.285714  0.4   

         74        75   76        77        78  
0  0.433333  0.498045  0.0  1.000000  0.622951  
1  0.183333  0.774510  0.0  0.333333  0.000000  
2  0.416667  0.078617  1.0  1.000000  0.967213  
3  0.433333  0.899764  1.0  1.000000  0.655738  
4  0.700000  0.037079  1.0  0.333333  0.409836  

[5 rows x 79 columns]

In [37]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd

X = numerical_scaled
y = target['TARGET_B']

# Fit SelectKBest and obtain scores for all features
model = SelectKBest(chi2, k=10)
model.fit(X, y)

# Create a DataFrame to store scores and corresponding feature names
df = pd.DataFrame({'Column': numerical.columns, 'Score': model.scores_})

# Sort the DataFrame by 'Score' in descending order and display the top 10 features
top_features = df.sort_values(by='Score', ascending=False).head(10)

print(top_features)

       Column       Score
313    RFA_2F  210.290810
305  CARDGIFT   27.516508
110      HVP1   26.474583
111      HVP2   25.757492
112      HVP3   21.545080
115      HVP6   19.261394
113      HVP4   14.874056
22       ETH2   13.034181
129       RP1   12.581538
130       RP2   11.022637


Checking correlation between the remaining columns with each other

In [38]:
corr_matrix=temp.corr()
corr_matrix.shape

(79, 79)

In [39]:
X

array([[0.00000000e+00, 6.08247423e-01, 6.66666667e-01, ...,
        0.00000000e+00, 1.00000000e+00, 6.22950820e-01],
       [1.38885031e-05, 4.63917526e-01, 8.33333333e-01, ...,
        0.00000000e+00, 3.33333333e-01, 0.00000000e+00],
       [1.38885031e-05, 6.24862364e-01, 3.33333333e-01, ...,
        1.00000000e+00, 1.00000000e+00, 9.67213115e-01],
       ...,
       [1.38885031e-05, 6.08247423e-01, 6.66666667e-01, ...,
        1.00000000e+00, 6.66666667e-01, 5.40983607e-01],
       [0.00000000e+00, 5.87628866e-01, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.63934426e-01],
       [2.77770062e-05, 8.14432990e-01, 6.66666667e-01, ...,
        1.00000000e+00, 0.00000000e+00, 1.80327869e-01]])

In [40]:
X_train

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
79401      1  75.000000       4        6    2         0       31        10   
86429      0  53.000000       5        9    0         0       29        24   
76729      1  60.000000       5        1    5         0       42        16   
38838      1  77.000000       6        6    9         1       40        23   
83012      3  55.000000       5        2   21        33       27        29   
...      ...        ...     ...      ...  ...       ...      ...       ...   
21243      0  70.000000       3        9    5         2       37        10   
45891      2  66.000000       3        6    0         0       36        11   
42613      1  61.611649       5        9    0         0       35        29   
43567      1  76.000000       5        3    1         0       59        22   
68268      0  61.611649       2        9    0         0       32        26   

       WWIIVETS  LOCALGOV  ...  DOB_YR  DOB_MM  MINRDATE_YR  MINRDATE_MM  \
79401        68         6  ...      23       1           89            2   
86429        38         7  ...      45       1           96            2   
76729        62        10  ...      37       9           91           10   
38838        41         8  ...      21       1           88           11   
83012        18        12  ...      43       1           94            1   
...         ...       ...  ...     ...     ...          ...          ...   
21243        32        26  ...      27       8           95           12   
45891        62         4  ...      32       1           96            2   
42613        42        17  ...       0       2           87            1   
43567        31         3  ...      21       7           87           11   
68268        37         3  ...       0       2           90            2   

       MAXRDATE_YR  MAXRDATE_MM  LASTDATE_YR  LASTDATE_MM  FIRSTDATE_YR  \
79401           90           12           96            1            88   
86429           96            2           96            2            96   
76729           95           11           95           11            88   
38838           93            9           95           12            88   
83012           95            4           95            4            94   
...            ...          ...          ...          ...           ...   
21243           94           10           97            2            86   
45891           96            2           96            2            96   
42613           94           12           96            1            87   
43567           95           12           96            3            86   
68268           94            8           96           10            88   

       FIRSTDATE_MM  
79401             3  
86429             2  
76729             9  
38838            11  
83012             1  
...             ...  
21243            12  
45891             2  
42613             1  
43567             9  
68268             1  

[76329 rows x 337 columns]

In [45]:
X_test

array([[3.88878087e-04, 6.59793814e-01, 8.33333333e-01, ...,
        1.00000000e+00, 0.00000000e+00, 1.63934426e-01],
       [1.38885031e-05, 5.87628866e-01, 6.66666667e-01, ...,
        0.00000000e+00, 0.00000000e+00, 4.75409836e-01],
       [1.38885031e-05, 4.63917526e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 6.55737705e-02],
       ...,
       [0.00000000e+00, 5.05154639e-01, 6.66666667e-01, ...,
        0.00000000e+00, 0.00000000e+00, 9.67213115e-01],
       [0.00000000e+00, 6.24862364e-01, 1.66666667e-01, ...,
        1.00000000e+00, 0.00000000e+00, 8.85245902e-01],
       [1.38885031e-05, 6.70103093e-01, 8.33333333e-01, ...,
        1.00000000e+00, 3.33333333e-01, 2.45901639e-01]])

In [46]:
numericalX_train

array([[1.38885031e-05],
       [0.00000000e+00],
       [1.38885031e-05],
       ...,
       [1.38885031e-05],
       [1.38885031e-05],
       [0.00000000e+00]])

In [41]:
feature_data = pd.concat([temp, categorical], axis = 1)
feature_data

0         1         2         3         4         5         6  \
0      0.608247  0.666667  1.000000  0.343434  0.181818  0.555556  0.000000   
1      0.463918  0.833333  1.000000  0.555556  0.111111  1.000000  1.000000   
2      0.624862  0.333333  0.111111  0.292929  0.333333  0.111111  0.000000   
3      0.711340  0.000000  0.444444  0.141414  0.313131  0.000000  0.000000   
4      0.793814  0.333333  0.222222  0.090909  0.535354  1.000000  1.000000   
...         ...       ...       ...       ...       ...       ...       ...   
95407  0.624862  0.666667  1.000000  0.474747  0.111111  1.000000  1.000000   
95408  0.484536  1.000000  1.000000  0.434343  0.191919  1.000000  0.969697   
95409  0.608247  0.666667  1.000000  0.464646  0.202020  1.000000  1.000000   
95410  0.587629  1.000000  1.000000  0.353535  0.202020  0.777778  1.000000   
95411  0.814433  0.666667  0.888889  0.222222  0.272727  0.888889  1.000000   

              7         8         9  ...  DOB_YR  DOB_MM  MINRDATE_YR  \
0      0.353535  0.656566  0.929293  ...      37      12           92   
1      0.000000  0.000000  0.676768  ...      52       2           93   
2      0.020202  0.989899  0.969697  ...       0       2           91   
3      0.080808  0.929293  0.616162  ...      28       1           87   
4      0.000000  0.000000  0.020202  ...      20       1           93   
...         ...       ...       ...  ...     ...     ...          ...   
95407  0.000000  0.000000  0.787879  ...       0       2           96   
95408  0.000000  0.040404  0.919192  ...      50       1           96   
95409  0.000000  0.000000  0.828283  ...      38       1           96   
95410  0.000000  0.000000  0.929293  ...      40       5           90   
95411  0.000000  0.000000  0.868687  ...      18       1           88   

       MINRDATE_MM  MAXRDATE_YR  MAXRDATE_MM  LASTDATE_YR  LASTDATE_MM  \
0                8           94            2           95           12   
1               10           95           12           95           12   
2               11           92            7           95           12   
3               11           94           11           95           12   
4               10           96            1           96            1   
...            ...          ...          ...          ...          ...   
95407            2           96            2           96            2   
95408            3           96            3           96            3   
95409            3           95            1           96           10   
95410           11           96            8           97            1   
95411           12           93           12           96           12   

       FIRSTDATE_YR  FIRSTDATE_MM  
0                89            11  
1                93            10  
2                90             1  
3                87             2  
4                79             3  
...             ...           ...  
95407            96             2  
95408            96             3  
95409            94            10  
95410            86            12  
95411            88             3  

[95412 rows x 101 columns]

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

import numpy as np

# Assuming X_train is a NumPy array
numerical_indices = np.where(np.issubdtype(X_train.dtype, np.number))[0]
numericalX_train = X_train[:, numerical_indices]

#numerical is already scaled


numericalX_train   = X_train_treated_upsampled.select_dtypes(np.number)
numericalX_test    = X_test_treated.select_dtypes(np.number)
categoricalX_train = X_train_treated_upsampled.select_dtypes(object) 
categoricalX_test  = X_test_treated.select_dtypes(object) 


# Encoding the categorical

In [51]:
encoder = OneHotEncoder(drop='first').fit(categoricalX_train)
encoded_cat_train = encoder.transform(categoricalX_train).toarray()
X_train_encoded = pd.DataFrame(encoded_cat_train, columns=encoder.get_feature_names_out())

encoded_cat_test = encoder.transform(categoricalX_test).toarray()
X_test_encoded = pd.DataFrame(encoded_cat_test, columns=encoder.get_feature_names_out())

In [52]:
X_train=pd.concat([numericalX_train.reset_index(drop=True), X_train_encoded],axis=1)
X_test=pd.concat([numericalX_test.reset_index(drop=True),X_test_encoded],axis=1)

In [53]:
X_test

TCODE       AGE    INCOME   WEALTH1       HIT  MALEMILI   MALEVET  \
0      0.000483  0.659794  0.833333  1.000000  0.000000  0.000000  0.242424   
1      0.000017  0.587629  0.666667  1.000000  0.000000  0.000000  0.171717   
2      0.000017  0.463918  1.000000  0.888889  0.004149  0.000000  0.282828   
3      0.000000  0.624862  0.666667  1.000000  0.000000  0.000000  0.333333   
4      0.000000  0.463918  0.333333  0.222222  0.000000  0.494949  0.161616   
...         ...       ...       ...       ...       ...       ...       ...   
19078  0.000034  0.624862  0.166667  0.000000  0.000000  0.000000  0.313131   
19079  0.000000  0.690722  0.666667  0.222222  0.074689  0.000000  0.303030   
19080  0.000000  0.505155  0.666667  1.000000  0.000000  0.000000  0.222222   
19081  0.000000  0.624862  0.166667  0.222222  0.000000  0.000000  0.333333   
19082  0.000017  0.670103  0.833333  0.555556  0.008299  0.000000  0.343434   

       VIETVETS  WWIIVETS  LOCALGOV  ...  RFA_2A_E  RFA_2A_F  RFA_2A_G  \
0      0.424242  0.222222  0.090909  ...       0.0       1.0       0.0   
1      0.282828  0.424242  0.101010  ...       0.0       1.0       0.0   
2      0.444444  0.222222  0.020202  ...       0.0       0.0       1.0   
3      0.373737  0.494949  0.080808  ...       1.0       0.0       0.0   
4      0.323232  0.030303  0.090909  ...       0.0       1.0       0.0   
...         ...       ...       ...  ...       ...       ...       ...   
19078  0.262626  0.313131  0.060606  ...       1.0       0.0       0.0   
19079  0.232323  0.313131  0.070707  ...       0.0       1.0       0.0   
19080  0.121212  0.383838  0.080808  ...       0.0       1.0       0.0   
19081  0.262626  0.414141  0.121212  ...       1.0       0.0       0.0   
19082  0.292929  0.454545  0.131313  ...       1.0       0.0       0.0   

       GEOCODE2_B  GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  DOMAIN_A_T  \
0             0.0         0.0         0.0         0.0         0.0         0.0   
1             0.0         0.0         0.0         0.0         0.0         0.0   
2             0.0         0.0         0.0         0.0         1.0         0.0   
3             0.0         0.0         0.0         0.0         0.0         1.0   
4             1.0         0.0         0.0         0.0         0.0         1.0   
...           ...         ...         ...         ...         ...         ...   
19078         0.0         0.0         1.0         1.0         0.0         0.0   
19079         0.0         1.0         0.0         0.0         0.0         0.0   
19080         0.0         0.0         1.0         1.0         0.0         0.0   
19081         0.0         0.0         1.0         0.0         0.0         1.0   
19082         0.0         0.0         1.0         0.0         0.0         1.0   

       DOMAIN_A_U  
0             0.0  
1             1.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
19078         0.0  
19079         0.0  
19080         0.0  
19081         0.0  
19082         0.0  

[19083 rows x 354 columns]

In [54]:
X_train

TCODE       AGE    INCOME   WEALTH1       HIT  MALEMILI   MALEVET  \
0       0.000017  0.624862  0.166667  1.000000  0.000000  0.000000  0.363636   
1       0.000000  0.309278  0.333333  0.777778  0.012448  0.000000  0.191919   
2       0.000000  0.659794  0.166667  0.777778  0.082988  0.000000  0.343434   
3       0.000000  0.546392  1.000000  1.000000  0.000000  0.000000  0.323232   
4       0.000483  0.474227  0.333333  0.555556  0.037344  0.000000  0.303030   
...          ...       ...       ...       ...       ...       ...       ...   
144967  0.000483  0.587629  1.000000  0.222222  0.045643  0.010101  0.414141   
144968  0.000017  0.948454  0.333333  0.333333  0.058091  0.000000  0.494949   
144969  0.000052  0.711340  0.333333  1.000000  0.000000  0.000000  0.000000   
144970  0.000000  0.587629  0.666667  1.000000  0.082988  0.000000  0.313131   
144971  0.000000  0.624862  0.500000  0.888889  0.000000  0.010101  0.313131   

        VIETVETS  WWIIVETS  LOCALGOV  ...  RFA_2A_E  RFA_2A_F  RFA_2A_G  \
0       0.313131  0.292929  0.040404  ...       1.0       0.0       0.0   
1       0.111111  0.292929  0.111111  ...       0.0       1.0       0.0   
2       0.292929  0.212121  0.090909  ...       1.0       0.0       0.0   
3       0.464646  0.141414  0.060606  ...       0.0       1.0       0.0   
4       0.080808  0.727273  0.090909  ...       0.0       0.0       1.0   
...          ...       ...       ...  ...       ...       ...       ...   
144967  0.272727  0.515152  0.070707  ...       0.0       1.0       0.0   
144968  0.171717  0.333333  0.141414  ...       0.0       0.0       1.0   
144969  0.000000  0.000000  0.000000  ...       0.0       0.0       0.0   
144970  0.414141  0.282828  0.050505  ...       0.0       1.0       0.0   
144971  0.424242  0.161616  0.080808  ...       1.0       0.0       0.0   

        GEOCODE2_B  GEOCODE2_C  GEOCODE2_D  DOMAIN_A_R  DOMAIN_A_S  \
0              0.0         1.0         0.0         0.0         0.0   
1              0.0         1.0         0.0         1.0         0.0   
2              1.0         0.0         0.0         0.0         0.0   
3              1.0         0.0         0.0         0.0         1.0   
4              1.0         0.0         0.0         0.0         0.0   
...            ...         ...         ...         ...         ...   
144967         0.0         0.0         1.0         1.0         0.0   
144968         1.0         0.0         0.0         1.0         0.0   
144969         1.0         0.0         0.0         1.0         0.0   
144970         1.0         0.0         0.0         0.0         0.0   
144971         0.0         0.0         0.0         0.0         0.0   

        DOMAIN_A_T  DOMAIN_A_U  
0              1.0         0.0  
1              0.0         0.0  
2              1.0         0.0  
3              0.0         0.0  
4              0.0         0.0  
...            ...         ...  
144967         0.0         0.0  
144968         0.0         0.0  
144969         0.0         0.0  
144970         0.0         0.0  
144971         0.0         0.0  

[144972 rows x 354 columns]

In [55]:
y_train

79401    0
86429    0
76729    1
38838    0
83012    0
        ..
21243    0
45891    0
42613    1
43567    0
68268    0
Name: TARGET_B, Length: 76329, dtype: int64

In [56]:
trainset=pd.concat([X_train,y_train.reset_index(drop=True)],axis=1)


In [57]:
trainset['TARGET_B'].value_counts()


0.0    72486
1.0     3843
Name: TARGET_B, dtype: int64

In [58]:
category_0 = trainset[trainset['TARGET_B']==0]
print(category_0.shape)

category_1_upsampled = trainset[trainset['TARGET_B']== 1 ].sample(len(trainset[trainset['TARGET_B']==0]),replace=True)
print(category_1_upsampled.shape)

(72486, 355)
(72486, 355)


In [59]:
trainset_upsampled= pd.concat([category_0, category_1_upsampled], axis = 0) 
trainset_upsampled = trainset_upsampled.sample(frac=1) #randomize the rows

In [60]:
X_train = trainset_upsampled.drop(['TARGET_B'], axis=1)
y_train = trainset_upsampled['TARGET_B']

In [62]:
clf = RandomForestClassifier(max_depth=5, # max number of questions to ask
                             min_samples_split=20, # amount of rows still considered at every question
                             min_samples_leaf =20, # ultimate answer based on at least this many rows
                             #max_samples=0.8, # fraction of X-train to use in each tree
                             random_state=42)
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

y_pred = clf.predict(X_test)
display(y_test.value_counts())
display(confusion_matrix(y_test, y_pred))

0.6415583698921171
0.5561494523921815


0    18083
1     1000
Name: TARGET_B, dtype: int64

array([[10156,  7927],
       [  543,   457]])

In [63]:
#no of actual donors predicted as non-donors
#avg.donation=15

543*15

8145

In [64]:
#no .of non_donors predicted as donors
#cost per post=0.68

7927*(.68)

5390.360000000001

1. I had better results without feature selection - but if we want get more donation, we should reduce false negatives i.e. (543) by recall

2. if we want to reduce money spent on post to non-donors, we should reduce false positives i.e (7927) by precision


3. here we can see that getting more donations has a bigger impact - so we should optimize for that. 

In [65]:
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(max_depth=5,
                             min_samples_split=20,
                             min_samples_leaf =20,
                            # max_samples=0.8
                            )
cross_val_scores = cross_val_score(clf, X_train, y_train, cv=5,scoring='f1')
print(np.mean(cross_val_scores))

0.6426576911256351


In [66]:
print(cross_val_scores)

[0.63283542 0.63595161 0.63594933 0.66124561 0.64730648]


# Conclusion